"""Product keywords for the transparent category classifier.

Descriptions and names have greater weight than navigation. Missing matches and
equal scores remain unknown; these labels never affect Shopify/India acceptance.
"""

TAXONOMY = {
    "Skincare": [
        "skincare",
        "skin care",
        "face wash",
        "face serum",
        "moisturizer",
        "sunscreen",
    ],
    "Hair care": ["hair care", "haircare", "hair growth", "hair loss", "shampoo"],
    "Coffee & tea": ["coffee", "tea", "roastery", "matcha", "chai"],
    "Food & nutrition": [
        "protein",
        "cookies",
        "healthy snacks",
        "nutrition",
        "ghee",
        "superfood",
        "plant based",
        "snacks",
        "chocolate",
        "chocolates",
        "cakes",
        "bakery",
        "beverages",
        "peanut butter",
        "spices",
        "millets",
        "dry fruits",
        "energizing drink",
        "nuts",
        "snacking",
        "pickles",
        "pickle",
        "achar",
        "coconut oil",
        "proteins",
    ],
    "Apparel": [
        "clothing",
        "streetwear",
        "sarees",
        "saree",
        "shirts",
        "dresses",
        "apparel",
        "kurta",
        "kurtas",
        "t-shirts",
        "tshirts",
        "fashion",
        "ethnic wear",
        "lingerie",
        "underwear",
        "loungewear",
        "lehengas",
        "activewear",
        "active wear",
        "leggings",
        "sports bras",
        "jeans",
        "hoodies",
        "dhotis",
        "clothes",
        "children wear",
        "children's wear",
        "salwar kameez",
        "suits",
        "socks",
        "trousers",
        "workwear",
    ],
    "Home & living": [
        "home decor",
        "home décor",
        "furniture",
        "homeware",
        "cushions",
        "tableware",
        "bedding",
        "decor",
        "décor",
        "home and living",
        "home & living",
        "bedsheets",
        "bed sheets",
        "bed linen",
        "chairs",
        "office chairs",
        "sofas",
        "curtains",
        "carpets",
        "mattresses",
        "lamps",
        "candles",
        "water bottles",
        "fridge bottles",
        "steel bottle",
        "storage containers",
        "kitchenware",
        "cookware",
        "cutlery",
        "dinnerware",
        "copperware",
    ],
    "Beauty & fragrance": ["perfume", "fragrance", "incense", "cosmetics", "makeup"],
    "Electronics": [
        "headphones",
        "earphones",
        "audio",
        "electronics",
        "speakers",
        "projectors",
        "soundbars",
        "gadgets",
        "electronic accessories",
        "chargers",
        "power banks",
        "earbuds",
        "headsets",
    ],
    "Plants & gardening": ["plants", "gardening", "nursery"],
    "Pet supplies": ["pet food", "pet supplies", "dog food"],
    "Jewellery": ["jewellery", "jewelry", "necklace", "earrings"],
    "Bags & travel": [
        "luggage",
        "backpack",
        "backpacks",
        "travel bags",
        "handbags",
        "wallets",
        "leather bags",
        "handbag",
        "embroidered bags",
        "tote bags",
        "sling bags",
        "shoulder bags",
        "duffel bags",
        "messenger bags",
        "laptop bags",
    ],
    "Footwear": ["footwear", "shoes", "sneakers", "sandals", "slippers"],
    "Toys & games": [
        "toys",
        "board games",
        "action figures",
        "collectibles",
        "puzzles",
        "chess",
        "chess boards",
        "chess sets",
    ],
    "Car & motorcycle accessories": [
        "car accessories",
        "car mats",
        "seat cover",
        "motorcycle accessories",
        "riding gear",
    ],
    "Phone accessories": [
        "phone cases",
        "phone covers",
        "mobile covers",
        "iphone cases",
        "screen protectors",
    ],
    "Musical instruments": [
        "musical instruments",
        "music instrument",
        "guitars",
        "keyboards and pianos",
    ],
    "Stationery & art": [
        "stationery",
        "art supplies",
        "notebooks",
        "journals",
        "fountain pens",
    ],
    "Sports & fitness": [
        "sports equipment",
        "fitness equipment",
        "gym equipment",
        "yoga mats",
        "cricket bats",
    ],
    "Watches & eyewear": ["watches", "sunglasses", "eyewear", "eyeglasses"],
    "Gifts & personalization": [
        "personalized",
        "personalised",
        "custom gifts",
        "themed gifts",
        "gift shop",
        "greeting cards",
    ],
    "Bicycles & cycling": [
        "bicycles",
        "cycling",
        "bicycle accessories",
        "cycles",
        "cycle brand",
    ],
    "Books & education": [
        "books",
        "book series",
        "bookstore",
        "book shop",
        "educational charts",
        "question banks",
        "study material",
        "novels",
    ],
    "Health & wellness": [
        "ayurveda",
        "ayurvedic",
        "herbal products",
        "healthcare",
        "wellness products",
        "vitamins",
        "supplements",
        "diabetes",
        "medical supplies",
    ],
    "Home appliances": [
        "home appliances",
        "home appliance",
        "kitchen appliances",
        "vacuum cleaners",
        "room heaters",
        "kettles",
        "air purifiers",
        "water purifiers",
        "mixer grinders",
        "pressure cookers",
    ],
    "Cleaning & laundry": [
        "home & hygiene",
        "home hygiene",
        "cleaning products",
        "laundry",
        "detergent",
        "dishwash",
        "floor cleaner",
        "toilet cleaner",
        "cleaning supplies",
    ],
    "Baby & maternity": [
        "baby food",
        "baby care",
        "babycare",
        "baby products",
        "maternity",
        "diapers",
        "strollers",
        "baby essentials",
        "babywear",
    ],
    "Intimate wellness": [
        "intimacy",
        "intimate wellness",
        "sexual wellness",
        "personal massagers",
        "lubricants",
    ],
    "Solar & power": [
        "solar",
        "solar panels",
        "inverters",
        "inverter",
        "lithium batteries",
    ],
    "Security & access": [
        "digital lock",
        "smart locks",
        "door locks",
        "door hardware",
        "biometric",
        "security cameras",
        "safes",
    ],
    "Software & digital products": [
        "software",
        "digital downloads",
        "digital products",
        "website templates",
        "design templates",
        "online courses",
    ],
    "Fabrics & craft supplies": [
        "fabric store",
        "buy fabric",
        "fabrics",
        "dress materials",
        "sewing",
        "yarn",
        "craft supplies",
        "resin",
    ],
    "Photography & filmmaking": [
        "photography",
        "videography",
        "camera stabilizers",
        "camera sliders",
        "camera accessories",
        "filmmaking",
        "videomaking",
    ],
    "Flowers": ["fresh flowers", "flower delivery", "floral arrangements", "bouquets"],
}
